"""Console platform protocol."""

from __future__ import annotations

from typing import Any, Protocol

from runtime.session.session import RuntimeSession


class ConsolePlatform(Protocol):
    """Facade surface required by built-in console commands."""

    def version(self) -> str: ...
    def doctor(self) -> Any: ...
    def list_models(self) -> Any: ...
    def current_model(self) -> Any | None: ...
    def use_model(self, profile_name: str) -> Any: ...
    def analyze(self, paper_path: Any) -> Any: ...
    def discover(self, analysis: Any | None = None, *, paper_path: Any | None = None) -> Any: ...
    def plan(self, analysis: Any, discovery: Any) -> Any: ...
    def run_execution(self, *, run_id: Any | None = None, resume: bool = True) -> Any: ...
    def execution_status(self, run_id: Any | None = None) -> Any: ...
    def execution_report(self, run_id: Any | None = None) -> Any: ...
    def run_startup_profile(self) -> Any: ...
    def is_runtime_ready(self) -> bool: ...
    def is_session_active(self) -> bool: ...
    def close_session(self) -> None: ...
    def session(self) -> RuntimeSession: ...

    @property
    def settings(self) -> Any: ...

    @property
    def runtime(self) -> Any: ...
